### ISSUE TITLE
i can't find the executable.

### ISSUE THREAD

**Issue by Fareast07** [DjPopol/EzPPPwn#10]
Where is the executable for the EzPPPwn ?

**Comment by DjPopol** [comment]
There IS a problem with pppwnC++ nighly link.
The author must update them.

**Comment by DjPopol** [comment]
> Where is the executable for the EzPPPwn ?

Hi, 
You could find it here :
[PPPwnCpp DjPopol](https://github.com/DjPopol/PPPwn_cpp/releases/tag/PPPwnCpp%23v1.0.1)
I update my app tonight with new link.

**Comment by DjPopol** [comment]
Fixed with v1.22

**Comment by Fareast07** [comment]
> There IS a problem with pppwnC++ nighly link. The author must update them.

So I have to wait for them to update them until I can do anything, right ?
Also, should I download the gnu or aarch win x64 ?

**Comment by Fareast07** [comment]
> > Where is the executable for the EzPPPwn ?
> 
> Hi, You could find it here : [PPPwnCpp DjPopol](https://github.com/DjPopol/PPPwn_cpp/releases/tag/PPPwnCpp%23v1.0.1) I update my app tonight with new link.

Thank you, brother.

**Comment by Fareast07** [comment]
> > Where is the executable for the EzPPPwn ?
> 
> Hi, You could find it here : [PPPwnCpp DjPopol](https://github.com/DjPopol/PPPwn_cpp/releases/tag/PPPwnCpp%23v1.0.1) I update my app tonight with new link.

hold on, i have windows 10, x64, i think the file you sent me is not the adequate format.

**Comment by DjPopol** [comment]
> > > Where is the executable for the EzPPPwn ?
> > 
> > 
> > Hi, You could find it here : [PPPwnCpp DjPopol](https://github.com/DjPopol/PPPwn_cpp/releases/tag/PPPwnCpp%23v1.0.1) I update my app tonight with new link.
> 
> hold on, i have windows 10, x64, i think the file you sent me is not the adequate format.

Juste use EzPPPwn v1.22 it download the right version automatiquely

**Comment by Fareast07** [comment]
Thanks.
